name: Mirror to nate-debug

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to nate-debug/natesoftware
        run: |
          git remote add mirror https://nate-debug:${{ secrets.MIRROR_TOKEN }}@github.com/nate-debug/natesoftware.git
          git push mirror main --force
